name: Build and Publish

on:
  push:
    branches:
      - main

env:
  AKS_RESOURCE_GROUP: aks-demo-alb-rg
  AKS_CLUSTER_NAME: demo
  NAMESPACE: demo2112

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Login in Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME

      - name: Deploy to AKS
        run: sed -i "s/\$IMAGE_TAG/${{ github.sha }}/" k8s/application.yaml && kubectl apply -f k8s/